pkgname wf053116b
confid 486
nodeid unxrh7
httpport 51364
wfcontext /ibi_apps
mrid autoadmuser02
mrpass 
mridbas autobasuser08
mrpassbas 
mridadv autoadvuser04
mrpassadv 
mriddev autodevuser82
mrpassdev 
mridgadmin autogadmuser01
mrpassgadmin
clientid bigscm23
browser chrome
browser_driver D:\chromedriver.exe
repository_type apachederby
installdir d:\486
project_id P292
suite_id S19901
group_id G520454
group_name V5 Personal Page Sharing and selecting links to existing pages
suite_type homepage