pkgname wf053116b
confid 486
nodeid unxrh7
httpport 11864
wfcontext /ibi_apps
mrid autodevuser202
mrpass
mriddev autodevuser202
mrpassdev 
clientid bigscm23
browser chrome
browser_driver D:\chromedriver.exe
repository_type apachederby
installdir d:\486
project_id P292
suite_id S19901
group_id G513470
group_name Grid Style/Type Enhancement
reference_folder Retail Samples->Portal->Small Widgets
suite_type pagedesigner