pkgname wf053116b
confid 486
nodeid unxrh7
httpport 11964
wfcontext /ibi_apps
mrid autoadmuser02
mrpass 
mridbas autobasuser08
mrpassbas 
mridadv autoadvuser04
mrpassadv 
mriddev autodevuser82
mrpassdev 
clientid bigscm23
browser chrome
browser_driver D:\chromedriver.exe
repository_type apachederby
installdir d:\486
project_id P292
suite_id S19901
group_id G512418
group_name Action Bar Defaults for User Types
suite_type homepage