pkgname wf053116b
confid 486
nodeid unxrh7
httpport 11864
wfcontext /ibi_apps
mrid autodevuser40
mrpass
mriddev autodevuser40
mrpassdev
clientid bigscm23
browser chrome
browser_driver D:\chromedriver.exe
repository_type apachederby
installdir d:\486
project_id P292
suite_id S11397
group_id G435441
group_name Show_content_path
reference_folder Retail Samples->Portal->Small Widgets
suite_type pagedesigner