pkgname wf052118a
confid 486
nodeid unxrh7
httpport 11864
wfcontext /ibi_apps
mrid autoadmuser01
mrpass 
mridbas autobasuser04
mrpassbas 
mridadv autoadvuser01
mrpassadv 
mriddev autodevuser82
mrpassdev 
mridgadmin autogadmuser01
mrpassgadmin 
clientid bigscm23
browser Chrome
browser_driver D:\chromedriver.exe
repository_type apachederby
installdir d:\486
project_id P292
suite_id S11397
group_id G491057
suite_type homepage