pkgname wf052118a
confid 486
nodeid unxrh7
httpport 11864
wfcontext /ibi_apps
mrid autoadmuser07
mrpass 
mridbas autobasuser13
mrpassbas 
mridadv autoadvuser12
mrpassadv 
mriddev autodevuser101
mrpassdev 
mridgadmin autogadmuser01
mrpassgadmin 
clientid bigscm23
browser Chrome
browser_driver D:\chromedriver.exe
repository_type apachederby
installdir d:\486
project_id P292
suite_id S10660
group_id G491033
suite_type homepage