pkgname wf053116b
confid 486
nodeid unxrh7
httpport 51364
wfcontext /ibi_apps
mrid autoadmuser08
mrpass 
mridbas autobasuser59
mrpassbas 
mridadv autoadvuser13
mrpassadv 
mriddev autodevuser88
mrpassdev 
mridgadmin autogadmuser01
mrpassgadmin 
clientid bigscm23
browser chrome
browser_driver D:\chromedriver.exe
repository_type apachederby
installdir d:\486
project_id P292
suite_id S19901
group_id G520448
group_name V5-Create and edit portal
suite_type homepage