pkgname wf052118a
confid 486
nodeid unxrh7
httpport 11364
wfcontext /ibi_apps
mrid autoadmuser03
mrpass 
mridbas autobasuser09
mrpassbas 
mridadv autoadvuser05
mrpassadv 
mriddev autodevuser83
mrpassdev 
mridgadmin autogadmuser01
mrpassgadmin 
clientid bigscm23
browser Chrome
browser_driver D:\chromedriver.exe
repository_type apachederby
installdir d:\486 
project_id P292
suite_id S10660
suite_type homepage